### ISSUE TITLE
Settings icon hides behind the search toolbar when scrolling

### ISSUE THREAD

**Issue by helloseyedjafari** [islamversity/Reyan#48]
We should move the `Search Icon` to the right of the search toolbar
and move the `Settings Icon` to the left of the `SearchToolbar` when scrolling

<img src="https://user-images.githubusercontent.com/27624716/94359084-49a3af80-00a5-11eb-808e-872f6e83f8d3.png" width="350"/>

<img src="https://user-images.githubusercontent.com/27624716/94359082-46102880-00a5-11eb-9e44-3fe4776253a2.png" width="350"/>

**Comment by alirezanazari** [comment]
#52
